defaults:
  - machine: local
  - model: mapanything_distillation
  - dataset: bmvs_reduced
  - loss: distillation
  - train_params: distillation
  - distributed: default
  - wandb_config: distillation
  - _self_

output_dir: ${machine.output_dir}
base_dir: ${machine.base_dir}
sam2_path: ${machine.sam2_path}
config_json_path: ${machine.config_json_path}
root_data_dir: ${machine.root_data_dir}
mapanything_dataset_metadata_dir: ${machine.mapanything_dataset_metadata_dir}